### ISSUE TITLE
Help needed with Building Digsby

### ISSUE THREAD

**Issue by iliepandia** [ifwe/digsby#24]
This is a continuation of the Build discussion that started here:

https://github.com/tagged/digsby/pull/20

Now I am getting another error. I will copy paste the output of buildout below

```
.\Imaging-1.1.6\Scripts\viewer.py
.\Imaging-1.1.6\Tk\booster.txt
.\Imaging-1.1.6\Tk\install.txt
.\Imaging-1.1.6\Tk\pilbitmap.txt
.\Imaging-1.1.6\Tk\tkImaging.c
275 File(s) copied
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
running install
running build
running build_py
running build_ext
building '_imagingft' extension
C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\digsby\digsby-venv\PC\freetype2 -IlibImaging -Ic:\digsby\digsby-venv\include -Ic:\Python26\
include -Ic:\digsby\digsby-venv\PC /Tc_imagingft.c /Fobuild\temp.win32-2.6\Release\_imagingft.obj
_imagingft.c
C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\digsby\digsby-venv\lib /LIBPATH:c:\Python26\Libs /LIBPATH:c:\digsby\digsby-venv\libs /LIBP
ATH:c:\digsby\digsby-venv\PCbuild freetype.lib /EXPORT:init_imagingft build\temp.win32-2.6\Release\_imagingft.obj /OUT:build\lib.win32-2.6\_imagingft.pyd /IMPLIB:build\temp.win32-2.6\Release\_i
magingft.lib /MANIFESTFILE:build\temp.win32-2.6\Release\_imagingft.pyd.manifest
   Creating library build\temp.win32-2.6\Release\_imagingft.lib and object build\temp.win32-2.6\Release\_imagingft.exp
C:\Program Files\Microsoft SDKs\Windows\v7.0A\bin\mt.exe -nologo -manifest build\temp.win32-2.6\Release\_imagingft.pyd.manifest -outputresource:build\lib.win32-2.6\_imagingft.pyd;2

build\temp.win32-2.6\Release\_imagingft.pyd.manifest : general error c1010070: Failed to load and parse the manifest. The system cannot find the file specified.
error: command 'mt.exe' failed with exit status 31
While:
  Installing PIL.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\digsby\digsby-venv\lib\site-packages\zc.buildout-2.1.0-py2.6.egg\zc\buildout\buildout.py", line 1923, in main
    getattr(buildout, command)(args)
  File "c:\digsby\digsby-venv\lib\site-packages\zc.buildout-2.1.0-py2.6.egg\zc\buildout\buildout.py", line 604, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\digsby\digsby-venv\lib\site-packages\zc.buildout-2.1.0-py2.6.egg\zc\buildout\buildout.py", line 1358, in _call
    return f()
  File "c:\digsby\cmdrunner\cmdrunner.py", line 64, in install
    self.execute()
  File "c:\digsby\cmdrunner\cmdrunner.py", line 77, in execute
    run_commands(cmds, self.shell, self.check_return_code)
  File "c:\digsby\cmdrunner\cmdrunner.py", line 48, in run_commands
    raise Exception('non-zero return code for cmds:\n' + cmds)
Exception: non-zero return code for cmds:
cd c:\digsby\digsby-venv\downloads
curl -L http://effbot.org/media/downloads/Imaging-1.1.6.tar.gz --output c:\digsby\digsby-venv\downloads/Imaging-1.1.6.tar.gz
tar -xzf Imaging-1.1.6.tar.gz
touch c:\digsby\digsby-venv\PC\unistd.h
xcopy .\Imaging-1.1.6 c:\digsby\digsby-venv\parts\Imaging-1.1.6 /S /i /y
cd c:\digsby\digsby-venv\parts\Imaging-1.1.6
python setup.py install --install-lib="c:\digsby\digsby-venv\lib\site-packages" --install-scripts="c:\digsby\digsby-venv\Scripts"
xcopy .\build\lib.win32-2.6\*.pyd c:\digsby\digsby-venv\DLLs /S /i /y
Ilie Pandia@WIN-JA8FLFJFVVJ /c/digsby
```

**Comment by mikedougherty** [comment]
For now, here's a possible workaround:
I've made a copy of my virtualenv folder (which I just used to build a new installer), minus the 'downloads' and 'parts' directories, which are used for intermediate buildout steps. You can find the zip here:
https://www.dropbox.com/s/4usf1inai1z8qk0/digsby-venv.zip

---

I'm a bit concerned though about the unfollow-able setup instructions. When @kevinw and I set up buildout, we were able to perform the whole process several times on different machines from scratch, and since then I've been able to do it on a VM twice as well. I'm not sure what sorts of things could be substantially different to cause this to fail. In the mean time I'm googling around some of the error messages you posted in hopes for a lead.

**Comment by iliepandia** [comment]
Hi,

Thanks for the reply.

The main problem is that I did not find VC2008 and I had to install VC2010 (closest match I could find).

I've worked in projects done in VC, and with every upgrade, none of them compiled properly and required manual configuration and setup to get it to work again. So, it may help if you have an archive with VC2008++ that is OK to share with others (and I think the express version is OK). 

I'll give it a try with the ZIP you've sent me.

**Comment by iliepandia** [comment]
Hi,

The virtualevn you've sent me seems to be missing "pip", since I get that error right from the start of buildout.

```
'pip' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mikedougherty** [comment]
pip should be installed with easy_install (setuptools) using your system python. from the readme:

```
 * [setuptools](http://pypi.python.org/packages/2.6/s/setuptools/setuptools-0.6c11.win32-py2.6.exe#md5=1509752c3c2e64b5d0f9589aafe053dc)
 * pip - install with `c:\Python26\Scripts\easy_install pip`
```

More importantly though, you shouldn't have to run buildout - buildout is used to set up the virtualenv directory (and packages, and binary dependencies). Unless my memory is completely failing me, you should be able to just activate the virtualenv (`digsby-venv/scripts/activate`) and then run `python sanity.py` successfully.

**Comment by iliepandia** [comment]
Hm,

I've deleted my disby-venv and replaced it with yours. At that time, when I activate it, python and pip stop working.

With my original digsby-venv, when I actiavate it both python and pip work.

**Comment by mikedougherty** [comment]
Can you try running the steps 2-7 of the readme again, after unpacking digsby-venv.zip? 
1. `cd c:\digsby`
2. `c:\Python26\Scripts\virtualenv -p c:\python26\python.exe --distribute digsby-venv`
3. `digsby-venv\Scripts\activate.bat`
4. `python bootstrap.py`
5. `deactivate`
6. `digsby-venv\Scripts\activate.bat`
   - bootstrap modifies the activate script.

(edit: apparently github markdown doesn't care what numbers you put in, and re-numbered these for me. heh)

When I did this, it overwrote the python and pip that was in the venv, so I'm hoping that for you it'll put in a working version.

**Comment by iliepandia** [comment]
Hello,

I've managed to find a VS2008 Express ISO on the web.

So I have started the process, fresh, from the beginning. 

I had to add Cygwin\bin to path (for zip an unzip) and also Git\bin (for git).

Next I've run the buildout that apparently has run all the way through.

Next I've run that long "sanity.py" line. Everything was OK, except for "SIP" that was marked as Failed.
